"""One-command reproducibility for every research result.

    python -m solarflare.reproduce                # recompute everything + RESULTS.md
    python -m solarflare.reproduce --results-only # just rebuild RESULTS.md from the
                                                  # artifacts already on disk

Runs, in order (each step degrades gracefully if its data/network is missing):
  1. solarflare.scorecard                  -> skill_scorecard.json
  2. solarflare.storm_scorecard            -> storm_scorecard.json
  3. solarflare.experiments.gap_diagnosis  -> gap_diagnosis.json
  4. solarflare.experiments.noaa_baseline  -> noaa_baseline.json
then writes RESULTS.md — the human-readable summary of the whole research
finding, generated from the artifacts (never hand-edited, so it can't drift).

All experiments use fixed seeds and train in-memory (the deployed model is
untouched). Dataset .npz files are inputs, not rebuilt here (see README for the
sharpdata/swansf_data build commands).
"""
from __future__ import annotations

import argparse
import json
import os

from .config import load_config


def _read(root: str, name: str):
    try:
        with open(os.path.join(root, name), "r", encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return None


def _num(v, fmt: str = "+.3f") -> str:
    try:
        return format(float(v), fmt)
    except (TypeError, ValueError):
        return "—"


def _ci(ci) -> str:
    return f" (95% CI {_num(ci[0])}..{_num(ci[1])})" if ci else ""


def _fmt_row(m: dict) -> str:
    fr = m.get("frozen", {})
    return (f"| {m['name']} ({m['detail']}) | {_num(m.get('benchmark_tss'), '.3f')} | "
            f"{_num(m.get('operational_tss'), '.3f')} | **{_num(m.get('gap'))}**{_ci(m.get('gap_ci'))} | "
            f"{_num(fr.get('gap'))}{_ci(fr.get('gap_ci'))} |")


def write_results_md(cfg: dict) -> str:
    root = cfg["_project_root"]
    sc = _read(root, "skill_scorecard.json")
    storm = _read(root, "storm_scorecard.json")
    diag = _read(root, "gap_diagnosis.json")
    noaa = _read(root, "noaa_baseline.json")

    L: list[str] = []
    add = L.append
    add("# Helios — Research Results")
    add("")
    add("> Auto-generated by `python -m solarflare.reproduce` from the JSON artifacts. "
        "Do not hand-edit.")
    add("")
    add("**Research question:** do standard benchmark scores overstate the real-time "
        "operational skill of ML flare forecasts, and does training on live satellite "
        "data close the gap?")
    add("")

    if sc:
        add("## 1. The benchmark-vs-operational gap (flare model)")
        add("")
        yrs = sc.get("test_sets", {}).get("operational_years", [])
        add(f"Benchmark test: {sc['test_sets']['benchmark']}. Operational test years: "
            f"{', '.join(map(str, yrs))}.")
        add("")
        add("| Model | Benchmark TSS | Operational TSS (mean) | Gap (peak) | Gap (frozen threshold) |")
        add("|---|---|---|---|---|")
        for m in sc.get("models", []):
            add(_fmt_row(m))
        add("")
        for m in sc.get("models", []):
            if m.get("benchmark_note"):
                add(f"- *{m['name']}*: {m['benchmark_note']}.")
        f = sc.get("findings", {})
        add(f"- Benchmarks overstate operational skill: **{f.get('benchmarks_overstate')}** "
            f"— gap {_num(f.get('overstatement_gap'))}{_ci(f.get('overstatement_gap_ci'))}, "
            f"positive in every tested year: {f.get('gap_positive_every_year')}.")
        add(f"- With a pre-committed (deployment) threshold the benchmark-trained gap is "
            f"{_num(f.get('frozen_overstatement_gap'))}{_ci(f.get('frozen_overstatement_gap_ci'))}.")
        add(f"- Live training closes the gap: **{f.get('live_training_closes_gap')}** "
            f"(benchmark-gap minus live-gap CI {f.get('live_minus_benchmark_gap_ci')} — "
            "negative means live training WIDENED it).")
        md = f.get("more_live_data")
        if md and "multi_year_operational_tss" in md:
            add(f"- MORE live data ({'+'.join(map(str, md.get('years_compared', [])))} tested): "
                f"single-year operational TSS {_num(md.get('single_year_operational_tss'), '.3f')} "
                f"vs multi-year {_num(md.get('multi_year_operational_tss'), '.3f')} — improves it: "
                f"**{md.get('more_data_improves_operational_skill')}** "
                f"(difference CI {md.get('multi_minus_single_operational_ci')}). "
                f"{md.get('note', '')}")
        elif md:                                      # legacy artifact shape
            add(f"- MORE live data ({'+'.join(map(str, md.get('years_compared', [])))} tested): "
                f"single-year gap {_num(md.get('single_year_gap_same_years'))} vs multi-year gap "
                f"{_num(md.get('multi_year_gap'))} — closes it: **{md.get('more_data_closes_gap')}** "
                f"(difference CI {md.get('single_minus_multi_gap_ci')}).")
        rc = f.get("recalibration") or {}
        bt = rc.get("benchmark_trained")
        if bt:
            add(f"- SELF-CORRECTION (threshold recalibrated on the first operational year, "
                f"frozen for the later years): benchmark-trained gap "
                f"{_num(bt.get('gap_before_same_years'))} → {_num(bt.get('gap_after'))}"
                f"{_ci(bt.get('gap_after_ci'))} on the SAME eval years; recovery "
                f"{_num(bt.get('recovery'))}{_ci(bt.get('recovery_ci'))} — significant: "
                f"**{bt.get('recovers_significantly')}**.")
        cf = rc.get("combined_fix")
        if cf:
            base = (f"- COMBINED FIX ({cf.get('description')}): operational TSS "
                    f"{_num(cf.get('operational_tss'), '.3f')} (CI {cf.get('operational_ci')}); "
                    f"recovery {_num(cf.get('recovery'))}{_ci(cf.get('recovery_ci'))}, "
                    f"significant: **{cf.get('recovers_significantly')}**")
            if cf.get("gap_after") is None:
                add(base + f". {cf.get('note') or 'No leakage-free benchmark cell — recovery and operational skill only.'}")
            else:
                closed = ("**gap closed** (point estimate ≤ 0)" if cf.get("gap_closed") else
                          "remaining gap statistically indistinguishable from zero (CI spans 0 — "
                          "absence of evidence, not proof of closure)" if cf.get("gap_not_significant")
                          else f"gap remains {_num(cf.get('gap_after'))}")
                add(base + f"; gap {_num(cf.get('gap_before_same_years'))} → {_num(cf.get('gap_after'))}"
                    f"{_ci(cf.get('gap_after_ci'))} on the same eval years — {closed}.")
        add("")
        add("Self-corrected deployment per model (recalibrate once, freeze, apply forward):")
        add("")
        add("| Model | Calibrated on | Eval years | TSS before | TSS after | Recovery |")
        add("|---|---|---|---|---|---|")
        for m in sc.get("models", []):
            r = m.get("recalibrated")
            if not r:
                continue
            add(f"| {m['name']} | {r['calibrated_on']} | "
                f"{'/'.join(map(str, r['eval_years']))} | {_num(r['before_tss_same_years'], '.3f')} | "
                f"**{_num(r['operational_tss'], '.3f')}** | {_num(r['recovery'])}{_ci(r['recovery_ci'])} |")
        add("")
        add("Per-year peak TSS (benchmark-trained model):")
        add("")
        bench = next((m for m in sc.get("models", []) if m["name"] == "Benchmark-trained"), None)
        if bench:
            add("| Year | Peak TSS | 95% CI | Frozen TSS | n windows | flares |")
            add("|---|---|---|---|---|---|")
            for yr, v in sorted(bench.get("by_year", {}).items()):
                add(f"| {yr} | {v['peak_tss']:.3f} | {v['peak_ci'][0]:.3f}..{v['peak_ci'][1]:.3f} "
                    f"| {v['frozen_tss']:.3f} | {v['n']} | {v['positives']} |")
        add("")
        add(f"*Method: {sc.get('method', {}).get('bootstrap', '')}. "
            f"{sc.get('method', {}).get('climatology_note', '')}.*")
        add("")

    dose = _read(root, "dose_response.json")
    if dose and dose.get("steps"):
        add("## 1b. Dose-response: gap vs. amount of live training data")
        add("")
        add(f"Fixed test years {dose.get('test_years')} for every step; {dose.get('method', '')}")
        add("")
        add("| Training years | n windows | Benchmark TSS | Operational TSS | Gap (peak) | Gap (frozen) |")
        add("|---|---|---|---|---|---|")
        for s in dose["steps"]:
            ys = s.get("train_years", [])
            add(f"| {'+'.join(map(str, ys))} | {s.get('n_train')} | "
                f"{_num(s.get('benchmark_tss'), '.3f')} | {_num(s.get('operational_tss'), '.3f')}"
                f" (CI {s.get('operational_ci')}) | **{_num(s.get('gap'))}**{_ci(s.get('gap_ci'))} | "
                f"{_num(s.get('frozen_gap'))}{_ci(s.get('frozen_gap_ci'))} |")
        add("")

    if storm:
        add("## 2. It generalises: the storm model shows the same optimism")
        add("")
        p, fz = storm.get("peak", {}), storm.get("frozen", {})
        add(f"Task: {storm.get('task')}. Winner: {storm.get('winner')}.")
        add("")
        add("| View | Benchmark TSS | Operational TSS | Gap |")
        add("|---|---|---|---|")
        add(f"| Peak | {p.get('benchmark_tss')} | {p.get('operational_tss')} | "
            f"**{p.get('gap'):+.3f}**{_ci(p.get('gap_ci'))} |")
        add(f"| Frozen threshold | {fz.get('benchmark_tss')} | {fz.get('operational_tss')} | "
            f"{fz.get('gap'):+.3f}{_ci(fz.get('gap_ci'))} |")
        add("")
        add(f"*{storm.get('method', {}).get('bootstrap', '')}.*")
        add("")

    if diag:
        add("## 3. Why the gap exists (mechanism diagnosis)")
        add("")
        a = diag.get("label_audit", {})
        add(f"- **Label-protocol audit** — SWAN-SF labels vs our HEK labeler on the same "
            f"windows: agreement {a.get('agreement')}, positive-class Jaccard "
            f"{a.get('positive_jaccard')} "
            f"(confusion: {a.get('confusion')}).")
        s = diag.get("distribution_shift", {})
        top = (s.get("top_shifted_features") or [{}])[0]
        add(f"- **Distribution shift** — median feature KS {s.get('median_ks_all_features')}; "
            f"most shifted: {top.get('feature')} (KS {top.get('ks')}).")
        d = diag.get("model_divergence", {})
        add(f"- **Model divergence** — Spearman rank correlation between the two models' "
            f"feature importances: {d.get('spearman_rank_correlation')}. "
            f"{d.get('reading', '')}")
        add("")

    if noaa:
        add("## 4. Against the official standard (NOAA SWPC)")
        add("")
        add(noaa.get("protocol", ""))
        add("")
        add("| Year | Forecaster | n days | Brier (lower=better) | Brier skill vs clim. | Peak TSS |")
        add("|---|---|---|---|---|---|")
        for yr, v in sorted(noaa.get("years", {}).items()):
            for who, key in (("NOAA official", "noaa_official"), ("Helios (deployed)", "helios_deployed")):
                r = v.get(key, {})
                add(f"| {yr} | {who} | {r.get('n_days')} | {r.get('brier')} | "
                    f"{r.get('brier_skill_vs_climatology')} | {r.get('peak_tss')} |")
        add("")
        add(f"*Caveat: {noaa.get('caveat', '')}*")
        add("")

    add("## Reproduce")
    add("")
    add("```bash")
    add("python -m solarflare.reproduce            # all experiments + this file")
    add("# individual pieces:")
    add("python -m solarflare.scorecard            # the 2x2 + bootstrap CIs")
    add("python -m solarflare.storm_scorecard      # storm generalisation check")
    add("python -m solarflare.experiments.gap_diagnosis")
    add("python -m solarflare.experiments.noaa_baseline")
    add("```")
    add("")
    add("Datasets (gitignored, rebuildable): `python -m solarflare.sharpdata --start "
        "YYYY-01-01 --end YYYY+1-01-01 --out data/sharp_live/dataset_YYYY.npz`; "
        "SWAN-SF partition via `python -m solarflare.swansf_data --tars "
        "data/swansf_full/partition1_instances.tar.gz --out "
        "data/sharp_live/dataset_swansf_p1.npz`.")
    add("")

    path = os.path.join(root, "RESULTS.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
    return path


def run(results_only: bool = False) -> dict:
    cfg = load_config()
    status = {}
    if not results_only:
        steps = [
            ("scorecard", lambda: __import__("solarflare.scorecard", fromlist=["run"]).run(cfg)),
            ("storm_scorecard", lambda: __import__("solarflare.storm_scorecard", fromlist=["run"]).run(cfg)),
            ("gap_diagnosis", lambda: __import__("solarflare.experiments.gap_diagnosis", fromlist=["run"]).run(cfg)),
            ("noaa_baseline", lambda: __import__("solarflare.experiments.noaa_baseline", fromlist=["run"]).run(cfg)),
            ("dose_response", lambda: __import__("solarflare.experiments.dose_response", fromlist=["run"]).run(cfg)),
        ]
        for name, fn in steps:
            print(f"\n===== {name} =====", flush=True)
            try:
                fn()
                status[name] = "ok"
            except Exception as exc:                      # noqa: BLE001 (degrade per step)
                status[name] = f"failed: {type(exc).__name__}: {exc}"
                print(f"  SKIPPED — {status[name]}", flush=True)
    path = write_results_md(cfg)
    status["results_md"] = path
    print(f"\nWrote {path}", flush=True)
    return status


def main():
    ap = argparse.ArgumentParser(description="Reproduce every research artifact.")
    ap.add_argument("--results-only", action="store_true",
                    help="only regenerate RESULTS.md from existing artifacts")
    args = ap.parse_args()
    print(json.dumps(run(results_only=args.results_only), indent=2))


if __name__ == "__main__":
    main()
